# Generated by Django 5.2.1 on 2025-06-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_category_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
