# Generated by Django 5.2.1 on 2025-06-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_name_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
