# Generated by Django 5.2.1 on 2025-06-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_title_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to='image_upload'),
            preserve_default=False,
        ),
    ]
