# Generated by Django 4.2.23 on 2025-06-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
